const GET_CART_REQUESTED = 'GET_CART_REQUESTED';
const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
const GET_CART_FAILURE = 'GET_CART_FAILURE';
const CHANGE_QTY = 'CHANGE_QTY';

export {
  GET_CART_REQUESTED,
  GET_CART_SUCCESS,
  GET_CART_FAILURE,
  CHANGE_QTY
}
